# Generated by Django 4.1.4 on 2023-01-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(blank=True, default='', max_length=100)),
                ('ticker', models.CharField(blank=True, default='', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
